name: Screenshots

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: screenshots-${{ github.ref }}
  cancel-in-progress: true

jobs:
  screenshots:
    name: Regenerate
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install llvmpipe and lavapipe for offscreen canvas
      run: |
        sudo apt-get update -y -qq
        sudo apt install -y libegl1-mesa-dev libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[examples]
    - name: Regenerate screenshots
      run: |
        pytest -v --regenerate-screenshots -k test_examples_compare examples
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots
        path: examples/screenshots
